import rigs from "./rigs.json";
import wellExtra from "./wellextra.json";

const calTotal = (data) => {
    let subTotal = 0;
    data.map((val) => {
        subTotal = subTotal + val.total;
    });

    return subTotal + subTotal * 0.1;
};

export const calCost = (data, timeline) => {
    let timeline_total = calTotal(timeline);
    const {
        rig_type,
        liner_casing_in_well,
        well_head_type,
        xmas_tree_type,
        surface_casing,
        intermmediate_casing,
        production_casing,
        liner_depth,
        igp_info,
        completions_type,
        completions_type_info,
        well_test_required,
        job_type,
        well_test_info,
        coring_required,
        coring_info,
    } = data;

    let costItems = [
        {
            sub_title: "Site Survey & Rig Operations",
            name: "HEAVY LAND RIG",
            unit: "per day",
            unit_cost: rigs.find((val) => val.name === rig_type).day_rate,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Site Survey & Rig Operations",
            name: "Marine Spread",
            unit: "per day",
            unit_cost: rigs.find((val) => val.name === rig_type).marine_spread,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Site Survey & Rig Operations",
            name: "Extra Catering ",
            unit: "per day",
            unit_cost: rigs.find((val) => val.name === rig_type).extra_catering,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Site Survey & Rig Operations",
            name: "Rig Charge-backs",
            unit: "per day",
            unit_cost: 500,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Site Survey & Rig Operations",
            name: "Rig Mob / Demobilisation",
            unit: "lumpsum",
            unit_cost:
                rigs.find((val) => val.name === rig_type).mob +
                rigs.find((val) => val.name === rig_type).demob,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Site Survey & Rig Operations",
            name: "Site Preparation",
            unit: "lumpsum",
            unit_cost: 1408678.5,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Site Survey & Rig Operations",
            name: "Well Head Repairs",
            unit: "lumpsum",
            unit_cost: 120370,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Site Survey & Rig Operations",
            name: "Location Dredging",
            unit: "lumpsum",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Site Survey & Rig Operations",
            name: "Rig Positioning Survey",
            unit: "lumpsum",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Site Survey & Rig Operations",
            name: "Rig Move",
            unit: "per day",
            unit_cost: rigs.find((val) => val.name === rig_type).day_rate * 0.8,
            quantity: rigs.find((val) => val.name === rig_type).rig_up,
            total: 0,
        },
        {
            sub_title: "Drilling Consumables",
            name: "Water",
            unit: "per bbl",
            unit_cost: 9507.14285714286,
            quantity: 11,
            total: 0,
        },
        {
            sub_title: "Drilling Consumables",
            name: '26" Hole',
            unit: "per bbl",
            unit_cost: 15,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Consumables",
            name: '16" Hole',
            unit: "per bbl",
            unit_cost: 23.2,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Consumables",
            name: '12.1/4" Hole',
            unit: "per bbl",
            unit_cost: 410,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Consumables",
            name: '8.1/2" Hole',
            unit: "per bbl",
            unit_cost: 288.96,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Consumables",
            name: '6" Hole',
            unit: "per bbl",
            unit_cost: 288.96,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Consumables",
            name: "Brine and clean out chemicals",
            unit: "per bbl",
            unit_cost: 94.15,
            quantity: 1250,
            total: 0,
        },
        {
            sub_title: "Drilling Consumables",
            name: "Base Oil Cushion",
            unit: "per bbl",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Consumables",
            name: '26" Rock (IADC 1-1-1)',
            unit: "each",
            unit_cost: 28000,
            quantity: 2,
            total: 0,
        },
        {
            sub_title: "Drilling Consumables",
            name: '16" Rock (IADC 1-1-6)',
            unit: "each",
            unit_cost: 24300,
            quantity: 2,
            total: 0,
        },
        {
            sub_title: "Drilling Consumables",
            name: '12 1/4" Rock (IADC 1-3-7)',
            unit: "each",
            unit_cost: 16500,
            quantity: 2,
            total: 0,
        },
        {
            sub_title: "Drilling Consumables",
            name: '12 1/4" PDC (IADC M323)',
            unit: "each",
            unit_cost: 55000,
            quantity: 2,
            total: 0,
        },
        {
            sub_title: "Drilling Consumables",
            name: '8 1/2" Rock (IADC 1-3-7)',
            unit: "each",
            unit_cost: 4622,
            quantity: 2,
            total: 0,
        },
        {
            sub_title: "Drilling Consumables",
            name: '8 1/2" PDC',
            unit: "each",
            unit_cost: 2,
            quantity: 2,
            total: 0,
        },
        {
            sub_title: "Drilling Consumables",
            name: '6" Rock',
            unit: "each",
            unit_cost: 3852,
            quantity: liner_casing_in_well === "YES" ? 2 : 0,
            total: 0,
        },
        {
            sub_title: "Drilling Consumables",
            name: '6" PDC',
            unit: "each",
            unit_cost: 0,
            quantity: liner_casing_in_well === "YES" ? 2 : 0,
            total: 0,
        },
        {
            sub_title: "Drilling Consumables",
            name: "Jets",
            unit: "each",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Consumables",
            name: 'Cement & Additives 30"',
            unit: "lumpsum",
            unit_cost: 80000,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Consumables",
            name: 'Cement & Additives 20"',
            unit: "lumpsum",
            unit_cost: 75000,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Consumables",
            name: 'Cement & Additives 13 3/8"',
            unit: "lumpsum",
            unit_cost: 56000,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Consumables",
            name: 'Cement & Additives 9 5/8"',
            unit: "lumpsum",
            unit_cost: 41415,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Consumables",
            name: 'Cement & Additives 7"',
            unit: "lumpsum",
            unit_cost: 35000,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Consumables",
            name: "P & A",
            unit: "lumpsum",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Tangibles",
            name: well_head_type,
            unit: "lumpsum",
            unit_cost:
                wellExtra
                    .find((val) => val.name === "Well Heads")
                    .meta.find((val) => val.meta_key === well_head_type)
                    ?.meta_value || 0,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Tangibles",
            name: xmas_tree_type,
            unit: "lumpsum",
            unit_cost:
                wellExtra
                    .find((val) => val.name === "Xmas Tree Type")
                    .meta.find((val) => val.meta_key === xmas_tree_type)
                    ?.meta_value || 0,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Tangibles",
            name: '30" Conductor',
            unit: "per ft",
            unit_cost: 787.5,
            quantity: parseInt(surface_casing) || 0,
            total: 0,
        },
        {
            sub_title: "Drilling Tangibles",
            name: '13 3/8" Intermediate Casing',
            unit: "per ft",
            unit_cost: 74.55,
            quantity: parseInt(intermmediate_casing) || 0,
            total: 0,
        },
        {
            sub_title: "Drilling Tangibles",
            name: '9 5/8" Production Casing',
            unit: "per ft",
            unit_cost: 280,
            quantity: parseInt(production_casing) || 0,
            total: 0,
        },
        {
            sub_title: "Drilling Tangibles",
            name: '7" Production Liner',
            unit: "per ft",
            unit_cost: 90,
            quantity: parseInt(liner_depth) || 0,
            total: 0,
        },
        {
            sub_title: "Drilling Tangibles",
            name: '13 3/8" Casing Pup Joints',
            unit: "per ft",
            unit_cost: 2956.8,
            quantity: 2,
            total: 0,
        },
        {
            sub_title: "Drilling Tangibles",
            name: '9 5/8" Production Casing Pup Joints',
            unit: "per ft",
            unit_cost: 5093,
            quantity: 2,
            total: 0,
        },
        {
            sub_title: "Drilling Tangibles",
            name: '7" Production Liner Pup Joints',
            unit: "per ft",
            unit_cost: 90,
            quantity: liner_casing_in_well === "YES" ? 2 : 0,
            total: 0,
        },
        {
            sub_title: "Drilling Tangibles",
            name: '13 3/8" Casing Coupling',
            unit: "per pc",
            unit_cost: 631,
            quantity: 2,
            total: 0,
        },
        {
            sub_title: "Drilling Tangibles",
            name: '9 5/8" Casing Coupling',
            unit: "per pc",
            unit_cost: 918,
            quantity: 2,
            total: 0,
        },
        {
            sub_title: "Drilling Tangibles",
            name: "GP Packers & Accessories",
            unit: "per zone",
            unit_cost: 199162,
            quantity:
                igp_info?.zones.filter((val) => val.igp === "YES").length || 0,
            total: 0,
        },
        {
            sub_title: "Drilling Tangibles",
            name: "SCSSVs, GLMs, Nipples, etc",
            unit: "per string",
            unit_cost: 237350,
            quantity: ["Single", "Single Selective"].includes(completions_type)
                ? 1
                : 2,
            total: 0,
        },
        {
            sub_title: "Drilling TangiblesDrilling Tangibles",
            name: "ESP Pump",
            unit: "each",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Tangibles",
            name: ["Single", "Single Selective"].includes(completions_type)
                ? completions_type_info?.turbing_size || ""
                : completions_type_info?.turbing_size_ls ||
                  completions_type_info?.turbing_size_ss ||
                  "",
            unit: "per ft",
            unit_cost:
                wellExtra
                    .find((val) => val.name === "Tubing Size")
                    .meta.find(
                        (val) =>
                            val.meta_key ===
                            (completions_type_info?.turbing_size ||
                                completions_type_info?.turbing_size_ls ||
                                completions_type_info?.turbing_size_ss)
                    )?.meta_value || 0,
            quantity: ["Single", "Single Selective"].includes(completions_type)
                ? completions_type_info?.turbing_length || 0
                : completions_type_info?.turbing_length_ls ||
                  completions_type_info?.turbing_length_ss ||
                  0,
            total: 0,
        },
        {
            sub_title: "Drilling Tangibles",
            name: "Pup Joints",
            unit: "lumpsum",
            unit_cost: 50264,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Tangibles",
            name: '36" Shoe',
            unit: "set",
            unit_cost: 18000,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Tangibles",
            name: '30" Shoe',
            unit: "set",
            unit_cost: 7000,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Tangibles",
            name: '13 3/8" Casing Shoe',
            unit: "set",
            unit_cost: 1521.47,
            quantity: 2,
            total: 0,
        },
        {
            sub_title: "Drilling Tangibles",
            name: '9 5/8" Casing Shoe',
            unit: "set",
            unit_cost: 1325.39,
            quantity: 2,
            total: 0,
        },
        {
            sub_title: "Drilling Tangibles",
            name: '7" Liner Shoe',
            unit: "set",
            unit_cost: 18000,
            quantity: liner_casing_in_well === "YES" ? 2 : 0,
            total: 0,
        },
        {
            sub_title: "Drilling Tangibles",
            name: '13 3/8" Float/Cent/Plugs',
            unit: "set",
            unit_cost: 4672.27,
            quantity: 2,
            total: 0,
        },
        {
            sub_title: "Drilling Tangibles",
            name: '9 5/8" Float/Cent Plugs',
            unit: "set",
            unit_cost: 3191.06,
            quantity: 2,
            total: 0,
        },
        {
            sub_title: "Drilling Tangibles",
            name: '7" Float/Cent/Plugs',
            unit: "set",
            unit_cost: 20479,
            quantity: liner_casing_in_well === "YES" ? 2 : 0,
            total: 0,
        },
        {
            sub_title: "Drilling Tangibles",
            name: '7" Liner hanger',
            unit: "lumpsum",
            unit_cost: 347662,
            quantity: liner_casing_in_well === "YES" ? 1 : 0,
            total: 0,
        },
        {
            sub_title: "Drilling Tangibles",
            name: "Mud Line Suspension Gear",
            unit: "lumpsum",
            unit_cost: 156163,
            quantity: liner_casing_in_well === "YES" ? 1 : 0,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Solids Control Mob/Demob",
            unit: "per day",
            unit_cost: 10000,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "SCE Engineering (crew of 5)",
            unit: "per day",
            unit_cost: 2690,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Engineering Unit / Office",
            unit: "per day",
            unit_cost: 100,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "SCE Equipment",
            unit: "per day",
            unit_cost: 2500,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "SBM Cuttings Disposal",
            unit: "per day",
            unit_cost: 290,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Skip and Ship",
            unit: "per day",
            unit_cost: 1000,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "AEA Medic & Equipment",
            unit: "per day",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "AEA Mob Fee",
            unit: "per day",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Fishing Equipment Rental",
            unit: "per day",
            unit_cost: 1151.69,
            quantity: 14,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Fishing Engineer",
            unit: "per day",
            unit_cost: 1350,
            quantity: 10,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: 'Cut & pull 30"',
            unit: "lumpsum",
            unit_cost: 75000,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: 'Cut & pull 13-3/8" Casing',
            unit: "lumpsum",
            unit_cost: 75000,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: 'Cut & pull 9-5/8" Casing',
            unit: "lumpsum",
            unit_cost: 75000,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: '36"Hole Opener',
            unit: "lumpsum",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Redress",
            unit: "lumpsum",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Stabs Rental",
            unit: "per day",
            unit_cost: 2500,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Stabs Redress",
            unit: "per redress",
            unit_cost: 2500,
            quantity: 2,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Drilling Jars",
            unit: "per day",
            unit_cost: 440,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Redress",
            unit: "per redress",
            unit_cost: 2200,
            quantity: 2,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Misc Rental",
            unit: "per day",
            unit_cost: 500,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Directional Drillers",
            unit: "see MWD",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Operating Rate Below Rotary",
            unit: "see MWD",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Core Engineers",
            unit: "per day",
            unit_cost: 2700,
            quantity: coring_required === "YES" ? 14 : 0,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Coring job setup fee",
            unit: "lumpsum",
            unit_cost: 38651,
            quantity: coring_required === "YES" ? 1 : 0,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Additional core footage cut 30ft",
            unit: "each",
            unit_cost: 10650,
            quantity:
                coring_required === "YES"
                    ? coring_info?.length_of_core_section / 30 || 0
                    : 0,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "MOB Core GR Log",
            unit: "each",
            unit_cost: 1500,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "GR Log Rental",
            unit: "per day",
            unit_cost: 420,
            quantity: 14,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "GR Log per Meter",
            unit: "per meter",
            unit_cost: 125,
            quantity: parseInt(production_casing) / 3.281 || 0,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Core Resin MOB",
            unit: "per run",
            unit_cost: 6000,
            quantity:
                coring_required === "YES"
                    ? coring_info?.no_of_core_runs || 0
                    : 0,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Core Resin Engineers",
            unit: "per day",
            unit_cost: 1100,
            quantity: coring_required === "YES" ? 14 : 0,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Core Resin Equipment Rental",
            unit: "per day",
            unit_cost: 420,
            quantity: coring_required === "YES" ? 14 : 0,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Core head rental, cost/m rec.",
            unit: "per meter",
            unit_cost: 1974.5,
            quantity:
                coring_required === "YES"
                    ? coring_info?.length_of_core_section / 3.281 || 0
                    : 0,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Drillpipe & Associated Eqpt Rental",
            unit: "lumpsum",
            unit_cost: 233757.05,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Sr. Mud Engineer",
            unit: "per day",
            unit_cost: 800,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Jr. Mud Engineer",
            unit: "per day",
            unit_cost: 150,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Mud Lab",
            unit: "per day",
            unit_cost: 100,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Engineering Unit / Office",
            unit: "per day",
            unit_cost: 0,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Cement unit / Equipment / Crew",
            unit: "per day",
            unit_cost: 4000,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Wellhead Installation",
            unit: "lumpsum",
            unit_cost: 58090,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Engineer rate on call-out",
            unit: "per day",
            unit_cost: 1500,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Casing Hammer",
            unit: "per day",
            unit_cost: 12000,
            quantity: 7,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: '30" Conductor (Hammer Crew)',
            unit: "per day",
            unit_cost: 3780,
            quantity: 7,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: '7" Casing Lump Sum',
            unit: "per day",
            unit_cost: 2420,
            quantity: liner_casing_in_well === "YES" ? timeline[6].total : 0,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: '7" Casing Crew',
            unit: "per day",
            unit_cost: 2460,
            quantity: liner_casing_in_well === "YES" ? timeline[6].total : 0,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: '13 3/8" Casing Lump Sum',
            unit: "per day",
            unit_cost: 2500,
            quantity: timeline[4].total + 4,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: '13 3/8" Casing Crew',
            unit: "per day",
            unit_cost: 2000,
            quantity: timeline[4].total + 4,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: '9 5/8" Casing Lump Sum',
            unit: "per day",
            unit_cost: 2420,
            quantity: timeline[5].total + 4,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: '9 5/8" Casing Crew',
            unit: "per day",
            unit_cost: 2460,
            quantity: timeline[5].total + 4,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Completion String Lump Sum",
            unit: "per day",
            unit_cost: 4840,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Completion String crew",
            unit: "per day",
            unit_cost: 6910,
            quantity: timeline[35].total + timeline[36].total,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Bridge Plug Running Equipments",
            unit: "per day",
            unit_cost: 10000,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Bridge Plug Running Crew",
            unit: "per day",
            unit_cost: 2000,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Diving / ROV Services",
            unit: "per day",
            unit_cost: 15000,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "ROV Personnel",
            unit: "per day",
            unit_cost: 8000,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "ROV Equipment",
            unit: "per day",
            unit_cost: 2460,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "MWD/LWD Standby ",
            unit: "per day",
            unit_cost: 13000,
            quantity: 10,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "MWD/LWD Operational",
            unit: "per day",
            unit_cost: 16000,
            quantity:
                timeline
                    .slice(5, 7)
                    .reduce((total, item) => total + item.total, 0) * 2,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Surface Equipment",
            unit: "per day",
            unit_cost: 1050,
            quantity:
                timeline
                    .slice(5, 7)
                    .reduce((total, item) => total + item.total, 0) * 2,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "LWD Crew",
            unit: "per day",
            unit_cost: 5000,
            quantity:
                timeline
                    .slice(5, 7)
                    .reduce((total, item) => total + item.total, 0) * 2,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: '8 1/4" TesTrak  (Operational- 1st 10 tests)',
            unit: "per day",
            unit_cost: 7425,
            quantity: 2,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: '8 1/4" TesTrak  (Operational - Subsequent tests)',
            unit: "per day",
            unit_cost: 6600,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: '8 1/4" TesTrak (Standby)',
            unit: "per day",
            unit_cost: 25968,
            quantity: 10,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: '6 3/4" TesTrak  (Operational- 1st 10 tests)',
            unit: "per test",
            unit_cost: 7425,
            quantity: 2,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: '6 3/4" TesTrak  (Operational - Subsequent tests)',
            unit: "per day",
            unit_cost: 6600,
            quantity: 2,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: '6 3/4" TesTrak (Standby)',
            unit: "per day",
            unit_cost: 25968,
            quantity: 10,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: '6 3/4" AziTrak (Operational)',
            unit: "per day",
            unit_cost: 14280,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: '6 3/4" AziTrak (Standby)',
            unit: "per day",
            unit_cost: 6800,
            quantity: 10,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "GyroTrak",
            unit: "per day",
            unit_cost: 7000,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Reservoir Navigation Services while drilling",
            unit: "lumpsum",
            unit_cost: 120000,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Gyro Hand",
            unit: "per day",
            unit_cost: 1275,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Gyro Multi-shot Rental",
            unit: "per day",
            unit_cost: 2200,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Gyro Multi-shot Run Charge",
            unit: "per day",
            unit_cost: 20610,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Directional Drillers",
            unit: "per day",
            unit_cost: 4500,
            quantity:
                timeline
                    .slice(5, 7)
                    .reduce((total, item) => total + item.total, 0) * 2,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: '16" PDM / GR / RES (Operating)',
            unit: "per day",
            unit_cost: 8194,
            quantity: timeline[4].total,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: '16" PDM / GR / RES (Rental)',
            unit: "per day",
            unit_cost: 6290,
            quantity: 10,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: '9.5" & 6 3/4" AutoTrak Assy (Operational)',
            unit: "per day",
            unit_cost: 13600,
            quantity:
                timeline
                    .slice(5, 7)
                    .reduce((total, item) => total + item.total, 0) * 2,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: '9.5" & 6 3/4" AutoTrak Assy (Standby)',
            unit: "per day",
            unit_cost: 10200,
            quantity: 10,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: '8" & 6 3/4" Pulser Assy (Operational)',
            unit: "per day",
            unit_cost: 3400,
            quantity:
                timeline
                    .slice(5, 7)
                    .reduce((total, item) => total + item.total, 0) * 2,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: '8" & 6 3/4" Pulser Assy (Standby)',
            unit: "per day",
            unit_cost: 1700,
            quantity: 10,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: '8" & 6 3/4" APM',
            unit: "per day",
            unit_cost: 792,
            quantity:
                timeline
                    .slice(5, 7)
                    .reduce((total, item) => total + item.total, 0) * 2,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Wellbore cleanup tools & svcs",
            unit: "lumpsum",
            unit_cost: 53352,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Brine Filteration",
            unit: "per day",
            unit_cost: 1825.16,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "CT equipment rental",
            unit: "per day",
            unit_cost: 373390,
            quantity: 14,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Sampling Kits for N2 clean up flow",
            unit: "per day",
            unit_cost: 0,
            quantity: 14,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "CT Engineers",
            unit: "per day",
            unit_cost: 0,
            quantity: 14,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Surface Testing Mob/Demob",
            unit: "lumpsum",
            unit_cost: 0,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "N2 equipment Mob/Demob",
            unit: "lumpsum",
            unit_cost: 0,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "N2 Equipment Rental",
            unit: "per day",
            unit_cost: 122377,
            quantity: 14,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "N2 Consumables (est.)",
            unit: "lumpsum",
            unit_cost: 93871.7,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Gravel Pack Chemicals per zone",
            unit: "per zone",
            unit_cost: 72550.26,
            quantity:
                igp_info?.zones.filter((val) => val.igp === "YES").length || 0,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Frac Pack Chemicals",
            unit: "per zone",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Pumping Equipment & Personnel",
            unit: "per day",
            unit_cost: 4650,
            quantity:
                igp_info?.zones.filter((val) => val.igp === "YES").length ||
                0 * 9,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Slickline Equipment & Personnel",
            unit: "per day",
            unit_cost: 3026,
            quantity: timeline[36].total + 10,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Upper & lower completion running tools",
            unit: "per day",
            unit_cost: 6296.28,
            quantity:
                timeline
                    .slice(29, 35)
                    .reduce((total, item) => total + item.total, 0) + 4,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Upper & lower completion Personnel",
            unit: "per day",
            unit_cost: 3460,
            quantity:
                timeline
                    .slice(29, 35)
                    .reduce((total, item) => total + item.total, 0) + 18,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Perforating & DST Services",
            unit: "per zone",
            unit_cost: 427803.5,
            quantity:
                timeline[21].total < 0
                    ? 0
                    : well_test_required === "YES"
                    ? well_test_info.filter((val) => val.tcp_dst === "YES")
                          .length
                    : 0,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Perforating Footage Charges",
            unit: "per zone",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "TCP Running charge",
            unit: "per zone",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "TCP Rental",
            unit: "per zone",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Memory gages",
            unit: "each",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "DST Equipment & Services",
            unit: "lumpsum",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "X-mas Tree Services",
            unit: "lumpsum",
            unit_cost: 5000,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Welltest Services",
            unit: "per day",
            unit_cost: 6484.88,
            quantity:
                timeline
                    .slice(19, 28)
                    .reduce((total, item) => total + item.total, 0) - 3,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Personnel",
            unit: "per day",
            unit_cost: 5900,
            quantity:
                job_type === "Drilling"
                    ? 0
                    : well_test_required === "YES"
                    ? well_test_info.filter((val) => val.tcp_dst === "YES")
                          .length * 3
                    : 0,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Misc. Consumables",
            unit: "lumpsum",
            unit_cost: 880,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Services",
            name: "Misc. Material Supply",
            unit: "lumpsum",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Formation Evaluation",
            name: "Mud logging Unit - Operating",
            unit: "per day",
            unit_cost: 1060,
            quantity: timeline
                .slice(8, 11)
                .reduce((total, item) => total + item.total, 0),
            total: 0,
        },
        {
            sub_title: "Drilling Formation Evaluation",
            name: "Mud logging Unit Rates - Standby",
            unit: "per day",
            unit_cost: 500,
            quantity: timeline
                .slice(0, 11)
                .reduce((total, item) => total + item.total, 0),
            total: 0,
        },
        {
            sub_title: "Drilling Formation Evaluation",
            name: "2 x Data Engineer",
            unit: "per day",
            unit_cost: 840,
            quantity:
                timeline
                    .slice(8, 11)
                    .reduce((total, item) => total + item.total, 0) +
                timeline
                    .slice(0, 11)
                    .reduce((total, item) => total + item.total, 0),
            total: 0,
        },
        {
            sub_title: "Drilling Formation Evaluation",
            name: "2 x Mud logging Geologist",
            unit: "per day",
            unit_cost: 420,
            quantity:
                timeline
                    .slice(8, 11)
                    .reduce((total, item) => total + item.total, 0) +
                timeline
                    .slice(0, 11)
                    .reduce((total, item) => total + item.total, 0),
            total: 0,
        },
        {
            sub_title: "Drilling Formation Evaluation",
            name: "2 x Sample Catchers",
            unit: "per day",
            unit_cost: 290,
            quantity:
                timeline
                    .slice(8, 11)
                    .reduce((total, item) => total + item.total, 0) +
                timeline
                    .slice(0, 11)
                    .reduce((total, item) => total + item.total, 0),
            total: 0,
        },
        {
            sub_title: "Drilling Formation Evaluation",
            name: "6-men crew + Unit",
            unit: "per day",
            unit_cost: 2610,
            quantity:
                timeline
                    .slice(8, 11)
                    .reduce((total, item) => total + item.total, 0) +
                timeline
                    .slice(0, 11)
                    .reduce((total, item) => total + item.total, 0),
            total: 0,
        },
        {
            sub_title: "Drilling Formation Evaluation",
            name: "Standby -  No Personnel",
            unit: "per day",
            unit_cost: 500,
            quantity: timeline
                .slice(0, 11)
                .reduce((total, item) => total + item.total, 0),
            total: 0,
        },
        {
            sub_title: "Drilling Formation Evaluation",
            name: "Mob - Demob",
            unit: "lumpsum",
            unit_cost: 3000,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Formation Evaluation",
            name: "Exclusive Surface Equipment Rental",
            unit: "per day",
            unit_cost: 3828,
            quantity: timeline
                .slice(8, 13)
                .reduce((total, item) => total + item.total, 0),
            total: 0,
        },
        {
            sub_title: "Drilling Formation Evaluation",
            name: "Logging Crew Estimate Per Well",
            unit: "per day",
            unit_cost: 7200,
            quantity: timeline
                .slice(6, 11)
                .reduce((total, item) => total + item.total, 0),
            total: 0,
        },
        {
            sub_title: "Drilling Formation Evaluation",
            name: 'Logging charges 26" Hole',
            unit: "per day",
            unit_cost: 187000,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Formation Evaluation",
            name: 'Logging Charges 16" Hole',
            unit: "per day",
            unit_cost: 212000,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Formation Evaluation",
            name: 'Logging Charges 12 1/4" Hole - DSI',
            unit: "per day",
            unit_cost: 162000,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Formation Evaluation",
            name: 'Logging Charges 12 1/4" Hole - MDT',
            unit: "per day",
            unit_cost: 350000,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Formation Evaluation",
            name: 'Logging Charges 12 1/4" Hole - OBMI',
            unit: "per day",
            unit_cost: 90000,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Formation Evaluation",
            name: 'Logging Charges 12 1/4" Hole - CMR',
            unit: "per day",
            unit_cost: 100000,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Formation Evaluation",
            name: 'Logging Charges 12 1/4" Hole - VSP',
            unit: "per day",
            unit_cost: 125000,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Formation Evaluation",
            name: 'Logging Charges 12 1/4" Hole - Misc',
            unit: "per day",
            unit_cost: 50000,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Formation Evaluation",
            name: 'Logging Charges 8 1/2" Hole (all logs estimate)',
            unit: "lumpsum",
            unit_cost: 682483.8,
            quantity: liner_casing_in_well === "YES" ? 1 : 0,
            total: 0,
        },
        {
            sub_title: "Drilling Formation Evaluation",
            name: "SRO wireline",
            unit: "lumpsum",
            unit_cost: 76400,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Formation Evaluation",
            name: "Log processing",
            unit: "lumpsum",
            unit_cost: 125000,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Formation Evaluation",
            name: "Reservoir Navigation Svc",
            unit: "lumpsum",
            unit_cost: 150000,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Formation Evaluation",
            name: "Core Analysis",
            unit: "lumpsum",
            unit_cost: 250000,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Formation Evaluation",
            name: "PVT Analysis",
            unit: "lumpsum",
            unit_cost: 250000,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Formation Evaluation",
            name: "Operations Geologist",
            unit: "lumpsum",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Formation Evaluation",
            name: "G & G Timewriting",
            unit: "lumpsum",
            unit_cost: 500000,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Formation Evaluation",
            name: "London Office",
            unit: "lumpsum",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Formation Evaluation",
            name: "Wellsite Geologist",
            unit: "per day",
            unit_cost: 1700,
            quantity:
                timeline
                    .slice(8, 11)
                    .reduce((total, item) => total + item.total, 0) +
                timeline
                    .slice(0, 11)
                    .reduce((total, item) => total + item.total, 0),
            total: 0,
        },
        {
            sub_title: "Drilling Logistics",
            name: "Marine Transportation (Additional)",
            unit: "per day",
            unit_cost: rigs.find((rig) => rig.name === rig_type).day_rate || 0,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Drilling Logistics",
            name: "Cement Barge",
            unit: "per day",
            unit_cost: 1250,
            quantity: 43,
            total: 0,
        },
        {
            sub_title: "Drilling Logistics",
            name: "Pump Barge",
            unit: "per day",
            unit_cost: 1250,
            quantity: 43,
            total: 0,
        },
        {
            sub_title: "Drilling Logistics",
            name: "Tug Boat",
            unit: "per day",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Logistics",
            name: "1000MT Flat Barge",
            unit: "per day",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Logistics",
            name: "Coral Barge",
            unit: "per day",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Logistics",
            name: "Supply Boats ",
            unit: "per day",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Logistics",
            name: "Speed Boats",
            unit: "per day",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Logistics",
            name: "Field Security Vessel",
            unit: "per day",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Logistics",
            name: "House Boat (60 man)",
            unit: "per day",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Logistics",
            name: "House Boat (30 man)",
            unit: "per day",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Logistics",
            name: "Cew Boat (44 man)",
            unit: "per day",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Logistics",
            name: "Supply Boat Tank Cleaning",
            unit: "per day",
            unit_cost: 13000,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Logistics",
            name: "Spot Charter",
            unit: "per day",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Logistics",
            name: "Vessel Pilotage",
            unit: "per day",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Logistics",
            name: "Helicopter Services",
            unit: "per day",
            unit_cost: 10500,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Logistics",
            name: "Flight Charges",
            unit: "per day",
            unit_cost: 3500,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Logistics",
            name: "Tickets",
            unit: "lumpsum",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Logistics",
            name: "Rig Helifuel",
            unit: "lumpsum",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Logistics",
            name: "Oil Spill Contingency",
            unit: "lumpsum",
            unit_cost: 850,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Logistics",
            name: "Emergency Response",
            unit: "lumpsum",
            unit_cost: 680,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Logistics",
            name: "Port Base Operations",
            unit: "per day",
            unit_cost: 10000,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Drilling Logistics",
            name: "W/hse & Yard Handling Charges",
            unit: "per day",
            unit_cost: 100,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Drilling Logistics",
            name: "Trucking Services (Low Bed)",
            unit: "per day",
            unit_cost: 400,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Logistics",
            name: "Port Office/Administration",
            unit: "per day",
            unit_cost: 1400,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Logistics",
            name: "Power, Fuel & Water",
            unit: "per day",
            unit_cost: 7584,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Drilling Logistics",
            name: "Shipping/Freight Forwarding",
            unit: "per day",
            unit_cost: 6700,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Logistics",
            name: "Weather Forecast",
            unit: "lumpsum",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Logistics",
            name: "Weather Services",
            unit: "lumpsum",
            unit_cost: 100,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Logistics",
            name: "Communications",
            unit: "per day",
            unit_cost: 1200,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Drilling Personnel and Admin",
            name: "Safety Gear for Visitors/Personnel",
            unit: "per day",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Personnel and Admin",
            name: "Radioactive Training",
            unit: "lumpsum",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Personnel and Admin",
            name: "H2S Training & Monitoring Services",
            unit: "lumpsum",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Personnel and Admin",
            name: "EIA, Misc Training, Risk Assessments",
            unit: "lumpsum",
            unit_cost: 2500,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Personnel and Admin",
            name: "Drilling Supervisor (Day)",
            unit: "per day",
            unit_cost: 1800,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Drilling Personnel and Admin",
            name: "Drilling Supervisor (Night)",
            unit: "per day",
            unit_cost: 1700,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Drilling Personnel and Admin",
            name: "Flights / Accomodation / phones",
            unit: "per day",
            unit_cost: 200,
            quantity: 10,
            total: 0,
        },
        {
            sub_title: "Drilling Personnel and Admin",
            name: "Insurance",
            unit: "per day",
            unit_cost: 200000,
            quantity: 1,
            total: 0,
        },
        {
            sub_title: "Drilling Personnel and Admin",
            name: "Equipment All Risk",
            unit: "lumpsum",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Personnel and Admin",
            name: "Compensation : General Liability",
            unit: "lumpsum",
            unit_cost: 34500,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Personnel and Admin",
            name: "Company Fee",
            unit: "lumpsum",
            unit_cost: 45.36,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Personnel and Admin",
            name: "Placement fee",
            unit: "lumpsum",
            unit_cost: 0,
            quantity: 0,
            total: 0,
        },
        {
            sub_title: "Drilling Personnel and Admin",
            name: "Drilling Superintendent",
            unit: "per day",
            unit_cost: 1900,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Drilling Personnel and Admin",
            name: "Sr Completions Eng",
            unit: "per day",
            unit_cost: 1800,
            quantity: timeline_total,
            total: 0,
        },
        {
            sub_title: "Drilling Personnel and Admin",
            name: "QAQC Coordinator",
            unit: "per day",
            unit_cost: 650,
            quantity: timeline_total,
            total: 0,
        },
    ];

    costItems = costItems.map((val) => {
        val.total = val.quantity * val.unit_cost;

        return val;
    });

    return costItems;
};
